/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.55 (1.7.1)
 * Generated at: 2016-04-27 16:29:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.java.car.tp4.*;
import java.util.List;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");


Library l = (Library) application.getAttribute("library");

String author = request.getParameter("author");
if ( author != null ) {
    String title = request.getParameter("title");
    String year = request.getParameter("year");
    out.print("Auteur : "+author+"<br/>");
    out.print("Titre : "+title+"<br/>");
    out.print("Ann&eacute;e : "+year+"<br/><p/>");
    
    if(l != null) {
    	l.add(new Book(title, author, year));
    	out.println("<h3>Added book</h3>");
    } else {
    	out.println("<h3>No library found</h3>");
    }
}

if(l != null) {
	out.println("<h2>Books in Library</h2>");
	
	List<Book> books = l.getListBook();
	if(books != null) {
		out.println("<ul>");
		for(Book book : books) {
			out.println("<li><ul>");
		    out.println("<li>Title : "+book.getTitle()+"</li>");
		    out.println("<li>Author : "+book.getAuthor()+"</li>");
		    out.println("<li>Year : "+book.getYear()+"</li>");
		    out.println("</ul></li>");
		}
		out.println("</ul>");
	} else {
		out.println("<h3>no book list found</h3>");
	}
	
	out.println("<h2>Authors in Library</h2>");
	
	List<String> authors = l.getListAuthors();
	if(authors != null) {
		out.println("<ul>");
		for(String a : authors) {
		    out.println("<li>Author : "+a+"</li>");
		}
		out.println("</ul>");
	} else {
		out.println("<h3>no author found</h3>");
	}
} else {
   	out.println("<h3>No library found</h3>");
}

      out.write("\n");
      out.write("\n");
      out.write("<form action=\"form.jsp\">\n");
      out.write("Auteur : <input type=\"text\" name=\"author\" value='");
      out.print(request.getParameter("author"));
      out.write("'><br/>\n");
      out.write("Titre : <input type=\"text\" name=\"title\" value='");
      out.print(request.getParameter("title"));
      out.write("'><br/>\n");
      out.write("Ann&eacute;e : <input type=\"text\" name=\"year\" value='");
      out.print(request.getParameter("year"));
      out.write("'><br/>\n");
      out.write("<input type=\"submit\">\n");
      out.write("</form>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
